apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yiobr3y9f-go
  janus-idp.io/tekton: yiobr3y9f-go
  backstage.io/kubernetes-id: yiobr3y9f-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yiobr3y9f-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
