apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yiobr3y9f-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yiobr3y9f-go 
  name: yiobr3y9f-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yiobr3y9f-go 
